services:
  database:
    container_name: database_postgres_dwallet
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dwallet
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - .:/var/lib/postgresql
      # - /private/var/lib/postgresql:/var/lib/postgresql
    networks:
      - pucmg_nodejs_atv3

  api:
    container_name: api_pucmg_nodejs_atv3
    build: .
    image: node:16
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - pucmg_nodejs_atv3

networks:
  pucmg_nodejs_atv3:
